# Linear Regression with SGD

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 

In [13]:
url = 'C:/Users/Dave/Pictures/linearregre/envio.csv'
dataset = pd.read_csv(url, sep = ';')
dataset.head()

envio_t  numero_cajas  distancia
0    16.68             7        560
1    11.50             3        220
2    12.03             3        340
3    14.88             4         80
4    13.75             6        150

In [3]:
Y = dataset.iloc[:,:-2].values
X = dataset.iloc[:,1:].values
X,Y

(array([[   7,  560],
        [   3,  220],
        [   3,  340],
        [   4,   80],
        [   6,  150],
        [   7,  330],
        [   2,  110],
        [   7,  210],
        [  30, 1460],
        [   5,  605],
        [  16,  688],
        [  10,  215],
        [   4,  255],
        [   6,  462],
        [   9,  448],
        [  10,  776],
        [   6,  200],
        [   7,  132],
        [   3,   36],
        [  17,  770],
        [  10,  140],
        [  26,  810],
        [   9,  450],
        [   8,  635],
        [   4,  150]], dtype=int64),
 array([[16.68],
        [11.5 ],
        [12.03],
        [14.88],
        [13.75],
        [18.11],
        [ 8.  ],
        [17.83],
        [79.24],
        [21.5 ],
        [40.33],
        [21.  ],
        [13.5 ],
        [19.75],
        [24.  ],
        [29.  ],
        [15.35],
        [19.  ],
        [ 9.5 ],
        [35.1 ],
        [17.9 ],
        [52.32],
        [18.75],
        [19.83],
        [10.75]]))

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [5]:
X_train

array([[   9,  450],
       [   7,  132],
       [   4,  150],
       [   8,  635],
       [   9,  448],
       [   3,  220],
       [  16,  688],
       [   6,  462],
       [  30, 1460],
       [   2,  110],
       [   3,   36],
       [   6,  150],
       [   5,  605],
       [   7,  210],
       [  10,  140],
       [   4,   80],
       [   7,  560],
       [  26,  810],
       [  10,  776],
       [   4,  255]], dtype=int64)

In [6]:
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [7]:
regressor.score(X_test, Y_test)

0.8631658854722792

In [8]:
t = np.array([[4, 400]])

In [9]:
regressor.predict(t)

array([[14.65900438]])