# Linear Regression with OLS

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression

In [3]:
url = './Data/envio.csv'
dataset = pd.read_csv(url, sep = ';')
dataset.head()

envio_t  numero_cajas  distancia
0    16.68             7        560
1    11.50             3        220
2    12.03             3        340
3    14.88             4         80
4    13.75             6        150

In [3]:
inter = np.ones(25, dtype = int).reshape(1, -1)
inter = np.transpose(inter)

In [4]:
X_matrix = dataset.iloc[:,1:].values
Y = dataset.iloc[:,:-2].values

In [5]:
X = np.concatenate((inter, X_matrix), axis =1)
X = np.round(X)
X

array([[   1,    7,  560],
       [   1,    3,  220],
       [   1,    3,  340],
       [   1,    4,   80],
       [   1,    6,  150],
       [   1,    7,  330],
       [   1,    2,  110],
       [   1,    7,  210],
       [   1,   30, 1460],
       [   1,    5,  605],
       [   1,   16,  688],
       [   1,   10,  215],
       [   1,    4,  255],
       [   1,    6,  462],
       [   1,    9,  448],
       [   1,   10,  776],
       [   1,    6,  200],
       [   1,    7,  132],
       [   1,    3,   36],
       [   1,   17,  770],
       [   1,   10,  140],
       [   1,   26,  810],
       [   1,    9,  450],
       [   1,    8,  635],
       [   1,    4,  150]], dtype=int64)

In [6]:
X_t = np.transpose(X)
X_t

array([[   1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1],
       [   7,    3,    3,    4,    6,    7,    2,    7,   30,    5,   16,
          10,    4,    6,    9,   10,    6,    7,    3,   17,   10,   26,
           9,    8,    4],
       [ 560,  220,  340,   80,  150,  330,  110,  210, 1460,  605,  688,
         215,  255,  462,  448,  776,  200,  132,   36,  770,  140,  810,
         450,  635,  150]], dtype=int64)

In [7]:
trans = np.matmul(X_t, X)
trans

array([[     25,     219,   10232],
       [    219,    3055,  133899],
       [  10232,  133899, 6725688]], dtype=int64)

In [8]:
vec = np.matmul(X_t, Y)
vec

array([[   559.6 ],
       [  7375.44],
       [337071.69]])

In [9]:
inv = np.linalg.inv(trans)

In [10]:
Beta = np.matmul(inv, vec)
Beta

array([[2.34123115],
       [1.61590721],
       [0.01438483]])

In [14]:
t = np.array([[1, 4, 400]])

In [15]:
prediction = np.matmul(t, Beta)
prediction

array([[14.55879049]])